export const jobListData = [
  {
    id: 1,
    title: "Full-Stack Web Developer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Ho Chi Minh City, Vietnam",
    description:
      "We is looking for a Full-Stack Web Developer to join our dynamic team. You will be responsible for developing and maintaining web applications with 5 years of experience in the field.",
    tags: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    salary: "$100,000 - $120,000",
    isFeatured: true,
    isHot: true,
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "San Francisco, USA",
    description:
      "Join our team as a Backend Developer. You will be responsible for server-side logic and integration with the front-end.",
    tags: ["Node.js", "Express", "MongoDB"],
    salary: "$90,000 - $110,000",
    isFeatured: false,
    isHot: true,
  },
  {
    id: 3,
    title: "Data Scientist",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "New York, USA",
    description:
      "We are seeking a Data Scientist to analyze large amounts of raw information to find patterns.",
    tags: ["Python", "Machine Learning", "Data Analysis"],
    salary: "$110,000 - $130,000",
    isFeatured: true,
    isHot: false,
  },
  {
    id: 4,
    title: "Frontend Developer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "London, UK",
    description:
      "We are looking for a Frontend Developer to create engaging user interfaces.",
    tags: ["HTML", "CSS", "JavaScript"],
    salary: "$85,000 - $105,000",
    isFeatured: false,
    isHot: false,
  },
  {
    id: 5,
    title: "DevOps Engineer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Sydney, Australia",
    description:
      "Join our team as a DevOps Engineer to manage our infrastructure.",
    tags: ["AWS", "Docker", "Kubernetes"],
    salary: "$95,000 - $115,000",
    isFeatured: true,
    isHot: true,
  },
  {
    id: 6,
    title: "Mobile Developer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Tokyo, Japan",
    description:
      "We are looking for a Mobile Developer experienced in iOS and Android development.",
    tags: ["Swift", "Kotlin", "React Native"],
    salary: "$90,000 - $120,000",
    isFeatured: false,
    isHot: false,
  },
  {
    id: 7,
    title: "Project Manager",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Toronto, Canada",
    description:
      "We need an experienced Project Manager to lead cross-functional teams and ensure project success.",
    tags: ["Agile", "Scrum", "Project Planning"],
    salary: "$110,000 - $130,000",
    isFeatured: true,
    isHot: true,
  },
  {
    id: 8,
    title: "AI Researcher",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Zurich, Switzerland",
    description:
      "Join us as an AI Researcher to work on advanced machine learning models.",
    tags: ["Machine Learning", "Deep Learning", "Python"],
    salary: "$120,000 - $140,000",
    isFeatured: false,
    isHot: false,
  },
  {
    id: 9,
    title: "Cybersecurity Specialist",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Austin, USA",
    description:
      "We are hiring a Cybersecurity Specialist to protect our systems and data.",
    tags: ["Cybersecurity", "Network Security", "Encryption"],
    salary: "$105,000 - $125,000",
    isFeatured: true,
    isHot: true,
  },
  {
    id: 10,
    title: "Cloud Engineer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Dublin, Ireland",
    description:
      "We are looking for a Cloud Engineer to manage cloud infrastructure.",
    tags: ["AWS", "Azure", "Google Cloud"],
    salary: "$100,000 - $120,000",
    isFeatured: false,
    isHot: false,
  },
  {
    id: 11,
    title: "Marketing Specialist",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Madrid, Spain",
    description:
      "Join our team as a Marketing Specialist to execute digital campaigns.",
    tags: ["SEO", "Social Media", "Content Marketing"],
    salary: "$70,000 - $90,000",
    isFeatured: true,
    isHot: false,
  },
  {
    id: 12,
    title: "QA Engineer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Paris, France",
    description:
      "We're looking for a QA Engineer to ensure software quality.",
    tags: ["Testing", "Automation", "Selenium"],
    salary: "$80,000 - $100,000",
    isFeatured: false,
    isHot: true,
  },
  {
    id: 13,
    title: "Content Writer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Dubai, UAE",
    description:
      "We are looking for a Content Writer to produce high-quality web content.",
    tags: ["Writing", "SEO", "Content Strategy"],
    salary: "$60,000 - $80,000",
    isFeatured: false,
    isHot: false,
  },
  {
    id: 14,
    title: "Product Manager",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Amsterdam, Netherlands",
    description:
      "We need a Product Manager to oversee product development and strategy.",
    tags: ["Product Management", "Roadmaps", "User Research"],
    salary: "$115,000 - $135,000",
    isFeatured: true,
    isHot: true,
  },
  {
    id: 15,
    title: "Sales Manager",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Hong Kong, China",
    description:
      "Join us as a Sales Manager to drive our B2B sales initiatives.",
    tags: ["Sales", "B2B", "Customer Relations"],
    salary: "$90,000 - $110,000",
    isFeatured: false,
    isHot: false,
  },
  {
    id: 16,
    title: "Game Developer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Seoul, South Korea",
    description:
      "We are looking for a Game Developer to work on cutting-edge game development projects.",
    tags: ["Unity", "C#", "Game Design"],
    salary: "$95,000 - $115,000",
    isFeatured: true,
    isHot: true,
  },
  {
    id: 17,
    title: "Network Engineer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Mumbai, India",
    description:
      "Join us as a Network Engineer to manage and secure our network infrastructure.",
    tags: ["Networking", "Cisco", "Firewall"],
    salary: "$85,000 - $105,000",
    isFeatured: false,
    isHot: false,
  },
  {
    id: 18,
    title: "Data Engineer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Singapore",
    description:
      "We are hiring a Data Engineer to design and optimize data pipelines.",
    tags: ["SQL", "Big Data", "ETL"],
    salary: "$100,000 - $120,000",
    isFeatured: true,
    isHot: true,
  },
  {
    id: 19,
    title: "Machine Learning Engineer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Beijing, China",
    description:
      "We are looking for a Machine Learning Engineer to work on innovative ML projects.",
    tags: ["Python", "TensorFlow", "Scikit-Learn"],
    salary: "$120,000 - $140,000",
    isFeatured: false,
    isHot: false,
  },
  {
    id: 20,
    title: "UI/UX Designer",
    company: "Meta",
    companyBanner: "/dummy/company-banner.png",
    companyLogo: "/dummy/company-logo.png",
    location: "Berlin, Germany",
    description:
      "We are looking for a UI/UX Designer to turn our software into easy-to-use products for our clients.",
    tags: ["Figma", "Sketch", "Adobe XD"],
    salary: "$80,000 - $100,000",
    isFeatured: false,
    isHot: true,
  },
];
